---
title: "Final Project"
author: "Megha Khanna"
date: "04/15/2024"
---

#For my Final project, I have utilized various codes to analyze a dataset of newspaper publications concerning Jack the Ripper and his notorious murders.

My research questions are as follows:

1.  How does the frequency and context of terms associated with Jack the Ripper differ from those related to his victims in historical newspaper articles, and what does this tell us about societal attitudes towards crime and victimhood in late Victorian England?

2.  How did the topics covered in newspaper reports change before and after 1888, the year of Jack the Ripper's crimes? What can this reveal about the influence of these events on public discourse and media focus?

##Introduction

The infamous Jack the Ripper murders of 1888, targeting several sex workers in London’s Whitechapel district, became a stark illustration of the interplay between media sensationalism, public fear, and the stigmatization of sex workers. Jack the Ripper’s name continues to resonate throughout criminal history, not just for the horrific nature of the crimes but also for the media frenzy that erupted in late Victorian England.

This analysis aims to explore the differential portrayal of Jack the Ripper compared to his victims through the lens of historical newspaper articles. By analyzing the frequency and context of words used, we can gain insights into the narrative and societal perceptions constructed by the media of that era.
